import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import Head from 'next/head'
import BullEye from '../components/bullsEye'
import Headline from '../components/headline'
import HeadlineDescriptionVideo from '../components/headlineDescriptionVideo'
import Navbar from '../components/navbar'
import QuizCallSection from '../components/quizCall'
import ToolsSection from '../components/toolsSection'
import { getNetworkData } from '../queries/network'

export default function Home() {
  const { data } = useQuery(['network'], getNetworkData)

  if (!data) return <div>Nothing Found</div>
  const {
    homepage: { headline, sections }
  } = data
  console.log({ data })
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="bg-white-text h-screen">
        <Headline content={headline} />
        {sections.map(({ collection, item }, idx) => {
          switch (collection) {
            case 'bullsEye':
              return <BullEye elements={item} key={`bullsEye__${idx}`} />
            case 'headlineDescriptionVideo':
              return (
                <HeadlineDescriptionVideo
                  headline={item.headline}
                  description={item.description}
                  video={item.videoUrl}
                  key={`headlineDescriptionVideo__${idx}`}
                />
              )
            case 'quizCallSection':
              return (
                <QuizCallSection
                  ctaText={item.ctaText}
                  ctaTarget={item.ctaUrl}
                  description={item.description}
                  headline={item.headline}
                  image={item.image}
                  key={`quizCallSection__${idx}`}
                />
              )
            case 'tools':
              return (
                <ToolsSection
                  tools={item.tools}
                  headline={item.headline}
                  key={`tools__${idx}`}
                />
              )
            default:
              break
          }
        })}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(['network'], getNetworkData)
  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  }
}
