import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import PageComponent from 'components/page'
import Head from 'next/head'
import { queryNetworkContentPages } from 'requests/GRAPHQL/queryNetworkContentPages'
import Layout from '../components/layout'
import { queryNetwork } from '../requests'
import { getNetworkData } from '../requests/network'

export default function Home() {
  const { data: network, isLoading } = useQuery(['network'], queryNetwork)

  if (isLoading) return <div>is Loading</div>

  const { footerItems, navbarItems, socialMediaItems, homepage } = network
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        footerItems={footerItems}
        navbarItems={navbarItems}
        socials={socialMediaItems}
      >
        <PageComponent page={homepage} />
      </Layout>
    </>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(['network'], queryNetwork)
  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  }
}
