import { dehydrate, QueryClient } from '@tanstack/react-query'
import Head from 'next/head'
import Navbar from '../components/navbar'
import { getNetworkData } from '../queries/network'

export default function Home() {
  // const { } = useQuery(['network'], getNetworkData)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(['network'], getNetworkData)
  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  }
}
