import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import Head from 'next/head'
import BullEye from '../components/bullsEye'
import Footer from '../components/footer'
import Headline from '../components/headline'
import HeadlineDescriptionVideo from '../components/headlineDescriptionVideo'
import Layout from '../components/layout'
import Navbar from '../components/navbar'
import PageComponent from '../components/page'
import QuizCallSection from '../components/quizCall'
import ToolsSection from '../components/toolsSection'
import { getNetworkData } from '../queries/network'

export default function Home() {
  const { data } = useQuery(['network'], getNetworkData)

  if (!data) return <div>Nothing Found</div>
  const { homepage, footer } = data
  console.log({ data })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout page={homepage} footer={footer} />
    </>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(['network'], getNetworkData)
  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  }
}
